{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import DockerEngine.Model
import DockerEngine.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AuthConfig)
      propMimeEq MimeJSON (Proxy :: Proxy Body)
      propMimeEq MimeJSON (Proxy :: Proxy Body1)
      propMimeEq MimeJSON (Proxy :: Proxy Body2)
      propMimeEq MimeJSON (Proxy :: Proxy Body3)
      propMimeEq MimeJSON (Proxy :: Proxy BuildInfo)
      propMimeEq MimeJSON (Proxy :: Proxy ClusterInfo)
      propMimeEq MimeJSON (Proxy :: Proxy Config)
      propMimeEq MimeJSON (Proxy :: Proxy ConfigHealthcheck)
      propMimeEq MimeJSON (Proxy :: Proxy ConfigVolumes)
      propMimeEq MimeJSON (Proxy :: Proxy Container)
      propMimeEq MimeJSON (Proxy :: Proxy Container1)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummary)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummaryInner)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummaryInnerHostConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ContainerSummaryInnerNetworkSettings)
      propMimeEq MimeJSON (Proxy :: Proxy CreateImageInfo)
      propMimeEq MimeJSON (Proxy :: Proxy DeviceMapping)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointPortConfig)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSettings)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSettingsIPAMConfig)
      propMimeEq MimeJSON (Proxy :: Proxy EndpointSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorDetail)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ExecStartConfig)
      propMimeEq MimeJSON (Proxy :: Proxy GraphDriver)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfigLogConfig)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfigPortBindings)
      propMimeEq MimeJSON (Proxy :: Proxy IPAM)
      propMimeEq MimeJSON (Proxy :: Proxy IdResponse)
      propMimeEq MimeJSON (Proxy :: Proxy Image)
      propMimeEq MimeJSON (Proxy :: Proxy ImageDeleteResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ImageRootFS)
      propMimeEq MimeJSON (Proxy :: Proxy ImageSummary)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2001)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010Plugins)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010RegistryConfig)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20010RegistryConfigIndexConfigs)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20011)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20012)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20012Actor)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20013)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20014)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20015)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20016)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20017)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20018)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse20019)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2002)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2003)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2004)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2005)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2006)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2007)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2008)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2009)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200State)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse201)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2011)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2012)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse2013)
      propMimeEq MimeJSON (Proxy :: Proxy Mount)
      propMimeEq MimeJSON (Proxy :: Proxy MountPoint)
      propMimeEq MimeJSON (Proxy :: Proxy MountTmpfsOptions)
      propMimeEq MimeJSON (Proxy :: Proxy MountVolumeOptions)
      propMimeEq MimeJSON (Proxy :: Proxy MountVolumeOptionsDriverConfig)
      propMimeEq MimeJSON (Proxy :: Proxy Network)
      propMimeEq MimeJSON (Proxy :: Proxy NetworkConfig2)
      propMimeEq MimeJSON (Proxy :: Proxy NetworkContainer)
      propMimeEq MimeJSON (Proxy :: Proxy Node)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescription)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionEngine)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionEnginePlugins)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionPlatform)
      propMimeEq MimeJSON (Proxy :: Proxy NodeDescriptionResources)
      propMimeEq MimeJSON (Proxy :: Proxy NodeSpec)
      propMimeEq MimeJSON (Proxy :: Proxy NodeVersion)
      propMimeEq MimeJSON (Proxy :: Proxy Plugin)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfig)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigArgs)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigInterface)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigLinux)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigNetwork)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigRootfs)
      propMimeEq MimeJSON (Proxy :: Proxy PluginConfigUser)
      propMimeEq MimeJSON (Proxy :: Proxy PluginDevice)
      propMimeEq MimeJSON (Proxy :: Proxy PluginEnv)
      propMimeEq MimeJSON (Proxy :: Proxy PluginInterfaceType)
      propMimeEq MimeJSON (Proxy :: Proxy PluginMount)
      propMimeEq MimeJSON (Proxy :: Proxy PluginSettings)
      propMimeEq MimeJSON (Proxy :: Proxy Port)
      propMimeEq MimeJSON (Proxy :: Proxy ProcessConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ProgressDetail)
      propMimeEq MimeJSON (Proxy :: Proxy PushImageInfo)
      propMimeEq MimeJSON (Proxy :: Proxy Resources)
      propMimeEq MimeJSON (Proxy :: Proxy ResourcesBlkioWeightDevice)
      propMimeEq MimeJSON (Proxy :: Proxy ResourcesUlimits)
      propMimeEq MimeJSON (Proxy :: Proxy RestartPolicy)
      propMimeEq MimeJSON (Proxy :: Proxy Secret)
      propMimeEq MimeJSON (Proxy :: Proxy SecretSpec)
      propMimeEq MimeJSON (Proxy :: Proxy Service)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceEndpoint)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceEndpointVirtualIPs)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpec)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecMode)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecModeReplicated)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceSpecUpdateConfig)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceUpdateResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ServiceUpdateStatus)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpec)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecCAConfig)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecCAConfigExternalCAs)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecDispatcher)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecEncryptionConfig)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecOrchestration)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecRaft)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecTaskDefaults)
      propMimeEq MimeJSON (Proxy :: Proxy SwarmSpecTaskDefaultsLogDriver)
      propMimeEq MimeJSON (Proxy :: Proxy Task)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpec)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpec)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecContainerSpecDNSConfig)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecLogDriver)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecNetworks)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecPlacement)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResources)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResourcesLimits)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecResourcesReservation)
      propMimeEq MimeJSON (Proxy :: Proxy TaskSpecRestartPolicy)
      propMimeEq MimeJSON (Proxy :: Proxy TaskState)
      propMimeEq MimeJSON (Proxy :: Proxy TaskStatus)
      propMimeEq MimeJSON (Proxy :: Proxy TaskStatusContainerStatus)
      propMimeEq MimeJSON (Proxy :: Proxy ThrottleDevice)
      propMimeEq MimeJSON (Proxy :: Proxy Volume)
      propMimeEq MimeJSON (Proxy :: Proxy VolumeConfig)
      propMimeEq MimeJSON (Proxy :: Proxy VolumeUsageData)
      propMimeEq MimeJSON (Proxy :: Proxy HostConfig)
      
